### ISSUE TITLE
JS101 - What the Javascript?

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/javascript_curriculum#1]
I'm still not completely convinced that we need this lesson, but it _might_ be a good idea to include it.   The idea would be a bit about what JS is, how it works and maybe a bit of history as a good intro to the course before diving directly in the code.

**Comment by codyloyd** [comment]
nah.. forget it

**Comment by colevandersWands** [comment]
I know this is closed but I thought of something we've got that might work.
https://github.com/jankeLearning/content-md/blob/master/programming-and-paradigms/02-programming-languages.md

It's not too specific to JS, but it's important to understand.  specially since they'll be going on to do Ruby as well
