### ISSUE TITLE
Objects/this lesson

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/javascript_curriculum#23]
Before properly getting into OOP students should have a good grasp of Objects and scope/this

Much of this lesson could be handled elsewhere(Fundamentals 3 in JS101, Call/Apply/Bind, OOP)..but I'm leaving it as an issue for now in case there are issues we aren't covering

It could be that these get pulled into a series of 'OOP in JS' lessons

**Comment by colevandersWands** [comment]
https://github.com/jankeLearning/content-md/blob/master/js/01-objects-1.md

something like this could be a start

**Comment by codyloyd** [comment]
that is a good start.. it's much like what we have in our JS01 course.. I need to sit down and organize the whole Objects/Scope/this/Prototype/Classes/Etc sequence before we do too much more on any of these lessons.  All those things kind of depend on each other, and if we start tackling them individually it's going to end up more confusing than helpful

**Comment by colevandersWands** [comment]
- https://github.com/jankeLearning/content-md/blob/master/js/01-scope-context-1.md
- https://github.com/jankeLearning/content-md/blob/master/js/01-objects-1.md
- https://github.com/jankeLearning/content-md/blob/master/programming-and-paradigms/02-oop-single-objects.md
- https://github.com/jankeLearning/content-md/blob/master/js/03-scope-context-2.md
- https://github.com/jankeLearning/content-md/blob/master/programming-and-paradigms/03-oop-prototypes.md
- https://github.com/jankeLearning/content-md/blob/master/programming-and-paradigms/03-oop-factories.md
- https://github.com/jankeLearning/content-md/blob/master/programming-and-paradigms/04-three-pillars.md
- https://github.com/jankeLearning/content-md/blob/master/programming-and-paradigms/03-oop-classes.md
- https://github.com/jankeLearning/content-md/blob/master/programming-and-paradigms/12-adv-oop-in-js.md

**Comment by colevandersWands** [comment]
this is our whole series on this type of thing.
I can help you sort through it

**Comment by codyloyd** [comment]
awesome... I've been working on other stuff for a few days, but I'm ready to jump back into this project for a bit.

My plan of action is to first do a ton of research to get the topic straight in my own head..  I know the concepts of course, but knowing what's up and actually organizing/planning useful lessons is different lol.

Once I get a good general outline I'll fill it in with the content... on first glance your stuff looks good, if a bit unorganized 😄

**Comment by colevandersWands** [comment]
I've been pretty busy too, new and cooler job coming my way.  Part of it will be expanding jankelearning through january.   We're planning on focusing on good programming, collaboration, architecture, and product focused development.  This partly so we don't canibalize OdinProject, and partly because we see more of a need for this on the market than another 'full stack' program.

It is a bit scattered at the moment.  It's well organized in my head, which doesn't matter to anyone else.  and pretty well organized here: https://eliumacademy.github.io/Sepco/
In the interest of self-study and flexible class management we're working on a graph-based navigation instead of the gitbook.
