### ISSUE TITLE
DOM manipulation - onload event is not explained.

### ISSUE THREAD

**Issue by deksudo** [TheOdinProject/javascript_curriculum#272]
In the second practice of the DOM manipulation lesson, students are expected to make a GUI for their console game, but the window.onload event (or its equivalent) is not mentioned here, or in the previous lessons if i'm not missing anything. As a result, DOM selector methods execute before the page loads and the students are left confused as to why their code isn't selecting anything :) I was able to realize and fix this because I did the older course with the jQuery some time ago, where this concept was explained, but a first-time javascript user wouldn't know this.

**Comment by mindovermiles262** [comment]
The script link should be right above the closing `</body>` tag in the HTML so that the DOM is rendered before the Javascript is loaded.  By changing this you won't have to worry about the `window.onload` event

I'm not sure if this is included anywhere in the curriculum. Maybe @codyloyd would know.

**Comment by codyloyd** [comment]
added explanation

thanks for pointing this out.. and sorry it took me so dang long to get to fixing it
